package protocol;

public enum ProtocolType
{
    CONFIG_PIZZERIA_PROTOCOL,
    GET_ALL_PIZZERIA_PROTOCOL,
    GET_ALL_OPTION_SET_NAMES_PROTOCOL,
    GET_PIZZERIA_PROTOCOL,
    DELETE_PIZZERIA_PROTOCOL,
    UPDATE_BASE_PRICE_PROTOCOL,
    ADD_OPTION_TO_OPTION_SET_PROTOCOL,
}
